dist: xenial

jobs:
  include:
    - stage: "Lint"
      name: "Angular"
      language: node_js
      os: linux
      node_js: "10"
      script:
      - cd Client
      - npm i
      - npm run lint
    - # Second job - Backend
      name: "Loopback"
      language: node_js
      os: linux
      node_js: "10"
      script:
      - cd Backend
      - npm i
      - npm run lint
    - stage: "Build"
      name: "Angular"
      language: node_js
      os: linux
      node_js: "10"
      before_script:
      - cd Client
      - npm install -g @angular/cli
      - npm install
      script: 
      - ng build --prod
    - # Second job - Backend
      name: "Loopback"
      language: node_js
      os: linux
      node_js: "10"
      before_script:
      - cd Backend
      - npm install -g @loopback/cli
      - npm install
      script:
      - npm run build
