# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    cd Client
    npm install -g @angular/cli
    npm install
    ng build --prod --outputPath=dist/Client
  displayName: 'Build Angular'
  
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: Scheduler.csproj

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: Scheduler.csproj
    arguments: --configuration Release

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: Scheduler.csproj
    arguments: --configuration Release --output /home/vsts/work/1/a
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: /home/vsts/work/1/a
  condition: succeededOrFailed()
